apiVersion: v1
kind: Service
metadata:
  name: litemaas-agent-proxy
  labels:
    app.kubernetes.io/component: proxy
spec:
  type: ClusterIP
  ports:
    - port: 8400
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: litemaas-agent
    app.kubernetes.io/component: proxy
